# Generated by Django 5.0.4 on 2025-03-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unique_id',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
